### ISSUE TITLE
Please create an outside collaborator pull request 

### ISSUE THREAD

**Issue by dami-moj** [moj-analytical-services/github-outside-collaborators#102]
### usernames

didartls 

### names

Didar Hussain 

### emails

didar.hussain@lawsociety.org.uk

### org

The Law Society

### reason

collaborators on a data sharing and data linking project as part of Criminal Legal Aid Independent Review and Review of Civil Legal Aid

### added_by

Damilola.Oyebade@justice.gov.uk

### review_after

2024-11-01

### permission

pull

### repositories

https://github.com/moj-analytical-services/dsa_data_linking

**Comment by NickWalt01** [comment]
Hello @dami-moj, can you re-do the form please and use **dsa_data_linking** as the repositorie name

**Comment by AntonyBishop** [comment]
Completed
