### ISSUE TITLE
Please create an outside collaborator/s pull request

### ISSUE THREAD

**Issue by sheilz81** [moj-analytical-services/github-outside-collaborators#73]
### usernames

mikekatell
chrisdburr
SemeliHadjiloizou

### names

Michael Katell
Christopher Burr
Semeli Hadjiloizou

### emails

mkatell@turing.ac.uk
cburr@turing.ac.uk
shadjiloizou@turing.ac.uk

### org

The Alan Turing Institute

### reason

To collaborate on the MoJ's Data Science Ethics Framework

### added_by

sheilz81  sheila.ladva@justice.gov.uk

### review_after

2024-07-11

### permission

push

### repositories

data-science-ethics-framework

**Comment by NickWalt01** [comment]
Hi @sheilz81 approved, invites to the collaborators will have been sent out via the automation

**Comment by sheilz81** [comment]
great thanks so much
